//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDProject.ResourceCulture {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RDProjectCul {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RDProjectCul() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RDProject.ResourceCulture.RDProjectCul", typeof(RDProjectCul).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string btnAccept {
            get {
                return ResourceManager.GetString("btnAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justify Fard.
        /// </summary>
        internal static string btnFard {
            get {
                return ResourceManager.GetString("btnFard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string btnLogout {
            get {
                return ResourceManager.GetString("btnLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string btnNewEntry {
            get {
                return ResourceManager.GetString("btnNewEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string btnNewTransferRecord {
            get {
                return ResourceManager.GetString("btnNewTransferRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Accept.
        /// </summary>
        internal static string btnNotAccept {
            get {
                return ResourceManager.GetString("btnNotAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Deed.
        /// </summary>
        internal static string btnRegistrationDeed {
            get {
                return ResourceManager.GetString("btnRegistrationDeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string btnReset {
            get {
                return ResourceManager.GetString("btnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        internal static string btnScan {
            get {
                return ResourceManager.GetString("btnScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string btnTransferRecordDelete {
            get {
                return ResourceManager.GetString("btnTransferRecordDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data should be lose. Do you want to continue?.
        /// </summary>
        internal static string closeChildForm {
            get {
                return ResourceManager.GetString("closeChildForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to close the application?.
        /// </summary>
        internal static string closeMessage {
            get {
                return ResourceManager.GetString("closeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string colAddress {
            get {
                return ResourceManager.GetString("colAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caste.
        /// </summary>
        internal static string colCaste {
            get {
                return ResourceManager.GetString("colCaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string colFirstName {
            get {
                return ResourceManager.GetString("colFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string colIsDepartment {
            get {
                return ResourceManager.GetString("colIsDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Govt.
        /// </summary>
        internal static string colIsGovt {
            get {
                return ResourceManager.GetString("colIsGovt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kashmiri.
        /// </summary>
        internal static string colIsKashmiri {
            get {
                return ResourceManager.GetString("colIsKashmiri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string colLastName {
            get {
                return ResourceManager.GetString("colLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNIC.
        /// </summary>
        internal static string colNIC {
            get {
                return ResourceManager.GetString("colNIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        internal static string colPicPath {
            get {
                return ResourceManager.GetString("colPicPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumb.
        /// </summary>
        internal static string colThumb {
            get {
                return ResourceManager.GetString("colThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string dgvStatusColApproved {
            get {
                return ResourceManager.GetString("dgvStatusColApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caste.
        /// </summary>
        internal static string dgvStatusColCaste {
            get {
                return ResourceManager.GetString("dgvStatusColCaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNIC.
        /// </summary>
        internal static string dgvStatusColCNIC {
            get {
                return ResourceManager.GetString("dgvStatusColCNIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string dgvStatusColDate {
            get {
                return ResourceManager.GetString("dgvStatusColDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string dgvStatusColDescription {
            get {
                return ResourceManager.GetString("dgvStatusColDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father Name.
        /// </summary>
        internal static string dgvStatusColFatherName {
            get {
                return ResourceManager.GetString("dgvStatusColFatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string dgvStatusColMushtari {
            get {
                return ResourceManager.GetString("dgvStatusColMushtari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string dgvStatusColName {
            get {
                return ResourceManager.GetString("dgvStatusColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        internal static string dgvStatusColPhoto {
            get {
                return ResourceManager.GetString("dgvStatusColPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry No.
        /// </summary>
        internal static string dgvStatusColRegistryNo {
            get {
                return ResourceManager.GetString("dgvStatusColRegistryNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation.
        /// </summary>
        internal static string dgvStatusColRelation {
            get {
                return ResourceManager.GetString("dgvStatusColRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string dgvStatusColRemarks {
            get {
                return ResourceManager.GetString("dgvStatusColRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string dgvStatusColStatus {
            get {
                return ResourceManager.GetString("dgvStatusColStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string displayPic {
            get {
                return ResourceManager.GetString("displayPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tahoma.
        /// </summary>
        internal static string FontName {
            get {
                return ResourceManager.GetString("FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahi No:.
        /// </summary>
        internal static string lblBahiNumber {
            get {
                return ResourceManager.GetString("lblBahiNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        internal static string lblBasicInfo {
            get {
                return ResourceManager.GetString("lblBasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc No:.
        /// </summary>
        internal static string lblDocumentNumber {
            get {
                return ResourceManager.GetString("lblDocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East:.
        /// </summary>
        internal static string lblEast {
            get {
                return ResourceManager.GetString("lblEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible No.:.
        /// </summary>
        internal static string lblJildNumber {
            get {
                return ResourceManager.GetString("lblJildNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khatuni No:.
        /// </summary>
        internal static string lblKhatuniNo {
            get {
                return ResourceManager.GetString("lblKhatuniNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khewat No:.
        /// </summary>
        internal static string lblKhewatNo {
            get {
                return ResourceManager.GetString("lblKhewatNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string lblLogin {
            get {
                return ResourceManager.GetString("lblLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauza:.
        /// </summary>
        internal static string lblMauza {
            get {
                return ResourceManager.GetString("lblMauza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hissa:.
        /// </summary>
        internal static string lblMuntalka {
            get {
                return ResourceManager.GetString("lblMuntalka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North:.
        /// </summary>
        internal static string lblNorth {
            get {
                return ResourceManager.GetString("lblNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measles No:.
        /// </summary>
        internal static string lblQatah {
            get {
                return ResourceManager.GetString("lblQatah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By area of:.
        /// </summary>
        internal static string lblRaqba {
            get {
                return ResourceManager.GetString("lblRaqba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reg. No:.
        /// </summary>
        internal static string lblRegNo {
            get {
                return ResourceManager.GetString("lblRegNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string lblRegType {
            get {
                return ResourceManager.GetString("lblRegType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role:.
        /// </summary>
        internal static string lblRole {
            get {
                return ResourceManager.GetString("lblRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        internal static string lblSearchRegistry {
            get {
                return ResourceManager.GetString("lblSearchRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South:.
        /// </summary>
        internal static string lblSouth {
            get {
                return ResourceManager.GetString("lblSouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Registrar:.
        /// </summary>
        internal static string lblSubReg {
            get {
                return ResourceManager.GetString("lblSubReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tehsil:.
        /// </summary>
        internal static string lblTehsil {
            get {
                return ResourceManager.GetString("lblTehsil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string lblUserName {
            get {
                return ResourceManager.GetString("lblUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West:.
        /// </summary>
        internal static string lblWest {
            get {
                return ResourceManager.GetString("lblWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zar:.
        /// </summary>
        internal static string lblZar {
            get {
                return ResourceManager.GetString("lblZar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District:.
        /// </summary>
        internal static string lblZillah {
            get {
                return ResourceManager.GetString("lblZillah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string menuMain {
            get {
                return ResourceManager.GetString("menuMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string RightToLeft {
            get {
                return ResourceManager.GetString("RightToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string RightToLeftLayout {
            get {
                return ResourceManager.GetString("RightToLeftLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fard.
        /// </summary>
        internal static string tabFard {
            get {
                return ResourceManager.GetString("tabFard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mushtari.
        /// </summary>
        internal static string tabMushtari {
            get {
                return ResourceManager.GetString("tabMushtari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning.
        /// </summary>
        internal static string tabScanning {
            get {
                return ResourceManager.GetString("tabScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        internal static string tabTransfer {
            get {
                return ResourceManager.GetString("tabTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        internal static string toolDocument {
            get {
                return ResourceManager.GetString("toolDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string toolEnglish {
            get {
                return ResourceManager.GetString("toolEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string toolFind {
            get {
                return ResourceManager.GetString("toolFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string toolHelp {
            get {
                return ResourceManager.GetString("toolHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string toolLanguage {
            get {
                return ResourceManager.GetString("toolLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string toolMessage {
            get {
                return ResourceManager.GetString("toolMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string toolPrint {
            get {
                return ResourceManager.GetString("toolPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Deed.
        /// </summary>
        internal static string toolRegDeed {
            get {
                return ResourceManager.GetString("toolRegDeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urdu.
        /// </summary>
        internal static string toolUrdu {
            get {
                return ResourceManager.GetString("toolUrdu", resourceCulture);
            }
        }
    }
}
